### ISSUE TITLE
ImportError: cannot import name 'is_url'

### ISSUE THREAD

**Issue by darkmanAmazigh** [RasaHQ/rasa_core#1327]
i have started to learn this tuto, aand when i run this comand line

i got this error message

    	Traceback (most recent call last):
	  File "C:\python36\lib\runpy.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	  File "C:\python36\lib\runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "C:\python36\lib\site-packages\rasa_core\train.py", line 16, in <module>
		from rasa_core.agent import Agent
	  File "C:\python36\lib\site-packages\rasa_core\agent.py", line 38, in <module>
		from rasa_nlu.utils import is_url
	ImportError: cannot import name 'is_url'

i use 
       - rasa_core     0.12.0
       - rasa_nlu       0.12.0
       - tensorflow   1.10.0

how to solve it ?
thank you

**Comment by darkmanAmazigh** [comment]
when i upgrade NLU to 0.13.0; that solve the problem, but my comande line not run i got this

usage: train.py default [-h] [-o OUT] -d DOMAIN [--augmentation AUGMENTATION]
                    -c [CONFIG [CONFIG ...]] [--dump_stories]
                    [--debug_plots] (-s STORIES | --url URL | --core CORE)
                    [-v] [-vv] [--quiet]
train.py default: error: the following arguments are required: -c/--config
i try to follow this tutorial but not working ! what to put in the config file ?

**Comment by darkmanAmazigh** [comment]
i have created config file like this :

     language: "en"

     pipeline:
     - name: "intent_featurizer_count_vectors"
     - name: "intent_classifier_tensorflow_embedding"
     - name: "ner_duckling" # pre-trained entity recognition
     dimensions: ["email"]
Now when i run

python -m rasa_core.run -d models/dialogue
i got this in the console :

	$ python -m rasa_core.run -d models/dialogue

	2018-11-13 16:12:20 INFO     root  - Rasa process starting
	2018-11-13 16:12:20 WARNING  py.warnings  - C:\python36\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning:
	The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
	Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
	Alternatively include the following in your code:

	  import warnings
	  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

	In most other cases you should consider using 'safe_load(stream)'
	  data = yaml.load(stream)

	2018-11-13 16:12:24 INFO     root  - Rasa Core server is up and running on http://localhost:5005
	Bot loaded. Type a message and press enter (use '/stop' to exit):
	sad
	Exception in thread Thread-2:
	Traceback (most recent call last):
	  File "C:\python36\lib\threading.py", line 916, in _bootstrap_inner
		self.run()
	  File "C:\python36\lib\threading.py", line 864, in run
		self._target(*self._args, **self._kwargs)
	  File "C:\python36\lib\site-packages\rasa_core\channels\channel.py", line 291, in on_message_wrapper
		on_new_message(message)
	  File "C:\python36\lib\site-packages\rasa_core\agent.py", line 316, in handle_message
		return processor.handle_message(message)
	  File "C:\python36\lib\site-packages\rasa_core\processor.py", line 86, in handle_message
		self._predict_and_execute_next_action(message, tracker)
	  File "C:\python36\lib\site-packages\rasa_core\processor.py", line 305, in _predict_and_execute_next_action
		action, policy, confidence = self.predict_next_action(tracker)
	  File "C:\python36\lib\site-packages\rasa_core\processor.py", line 168, in predict_next_action
		probabilities, policy = self._get_next_action_probabilities(tracker)
	  File "C:\python36\lib\site-packages\rasa_core\processor.py", line 478, in _get_next_action_probabilities
		tracker, self.domain)
	  File "C:\python36\lib\site-packages\rasa_core\policies\ensemble.py", line 288, in probabilities_using_best_policy
		if (result.index(max_confidence) ==
	AttributeError: 'NoneType' object has no attribute 'index'
	
how it possible to solve this ?

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by darkmanAmazigh** [comment]
Hi @EPedrotti 
The problem is comming from python code or rasa ?

**Comment by akelad** [comment]
hold on, is your question about Core or NLU? Because you seem to be posting an nlu configuration file but then running a Core command?

**Comment by darkmanAmazigh** [comment]
Yes, i train and run with rasa_core,
now all thing work perfectly,
nex step, use web instead of shell
