### ISSUE TITLE
Intents not updating in interactive learning

### ISSUE THREAD

**Issue by samarth12** [RasaHQ/rasa_core#1194]
**Rasa Core version**:
Version: 0.11.12
**Python version**: 
Python 3.6.5 :: Anaconda, Inc.
**Operating system** (windows, osx, ...):
MacOS
**Issue**:
I am using the basic getting started bot to test interactive learning. The stories part seems to run great. I am also using a trained NLU model for the intents. 

When the user input is classified as a "None" intent. We have two options, to either correct and choose an intent from the existing list or choose the "other" option which allows us to define a new intent and then mark entities in the input sentence. 

If I choose an existing intent to correct an input that has been classified as "None" and then retrian the interactive learning model the model doesn't seem to capture the intent correction. Am I missing something? How does this work? I also checked if I need to train the NLU model to update it but I don't see any changes to the NLU file so that doesn't make sense. 

Secondly, if I choose the "other" option in case none of the intents match my input it asks me to name the intent followed by marking entities in that. That doesn't seem to work, it throws an error. 

Here is the error in the second case:

? **Next user input:  I need chinese food**
127.0.0.1 - - [2018-10-19 01:31:29] "POST /conversations/default/messages HTTP/1.1" 200 668 0.050945
127.0.0.1 - - [2018-10-19 01:31:29] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 668 0.000868
**? Is the NLU classification for 'I need chinese food' with intent 'None' correct
? What intent is it?       <other>
? Please type the intent name  food
? Please mark the entities using [value](type) notation  I need [chinese](cuisin
e) food**
127.0.0.1 - - [2018-10-19 01:31:54] "PUT /conversations/default/tracker/events HTTP/1.1" 200 388 0.001075
127.0.0.1 - - [2018-10-19 01:31:54] "POST /conversations/default/messages HTTP/1.1" 200 692 0.001299
2018-10-19 01:31:54 ERROR    rasa_core.server  - Caught an exception during prediction.
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/server.py", line 340, in predict
    responses = agent.predict_next(sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 317, in predict_next
    return processor.predict_next(sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 102, in predict_next
    self._get_next_action_probabilities(tracker)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 457, in _get_next_action_probabilities
    tracker, self.domain)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 216, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/policies/fallback.py", line 101, in predict_action_probabilities
    nlu_confidence = nlu_data["intent"].get("confidence", 1.0)
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 963, in handle_one_response
    self.run_application()
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 911, in run_application
    self.process_result()
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 895, in process_result
    for data in self.result:
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
TypeError: 'Response' object is not iterable
2018-10-19T08:31:54Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '53538', 'HTTP_HOST': 'localhost:5005', (hidden keys: 23)} failed with TypeError

127.0.0.1 - - [2018-10-19 01:31:54] "POST /conversations/default/predict HTTP/1.1" 500 161 0.003504
2018-10-19 01:31:54 ERROR    rasa_core.training.online  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 860, in record_messages
    finetune=finetune)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 589, in _predict_till_next_listen
    response = request_prediction(endpoint, sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 98, in request_prediction
    return _response_as_json(r)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 62, in _response_as_json
    response.raise_for_status()
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5005/conversations/default/predict

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```

```
md
## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:goodbye
- bye
- goodbye
- see you around
- see you later

## intent:mood_affirm
- yes
- indeed
- of course
- that sounds good
- correct

## intent:mood_deny
- no
- never
- I don't think so
- don't like that
- no way
- not really

## intent:mood_great
- perfect
- very good
- great
- amazing
- wonderful
- I am feeling very good
- I am great
- I'm good

## intent:mood_unhappy
- sad
- very sad
- unhappy
- bad
- very bad
- awful
- terrible
- not very good
- extremly sad
- so sad
```

Let me know if you need any additional information, thank you!

**Comment by samarth12** [comment]
Hey guys, do you have any update on this? Or is it better if I post this on the forum?

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.
(Sorry about the late response, but github was broken for most of yesterday)

**Comment by samarth12** [comment]
I tried running the same basic model for interactive learning. I am still not sure if and how adding completely new intents work with interactive learning. I just pulled the latest from the rasa_core. Here is the example:

? Next user input:  Hello
127.0.0.1 - - [2018-10-28 10:03:23] "POST /conversations/default/messages HTTP/1.1" 200 1241 0.059759
127.0.0.1 - - [2018-10-28 10:03:23] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 1241 0.001063
? Is the NLU classification for 'Hello' with intent 'greet' correct?  Yes
127.0.0.1 - - [2018-10-28 10:03:25] "POST /conversations/default/predict HTTP/1.1" 200 1628 0.160749
127.0.0.1 - - [2018-10-28 10:03:25] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 1241 0.001098
------
Chat History

 #    Bot                        You        
────────────────────────────────────────────
 1    action_listen                         
────────────────────────────────────────────
 2                                    Hello 
                         intent: greet 0.96 
------
? The bot wants to run 'utter_greet', correct?  Yes
127.0.0.1 - - [2018-10-28 10:03:27] "POST /conversations/default/execute HTTP/1.1" 200 1521 0.003258
127.0.0.1 - - [2018-10-28 10:03:27] "POST /conversations/default/predict HTTP/1.1" 200 1829 0.003593
127.0.0.1 - - [2018-10-28 10:03:27] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 1442 0.001100
------
Chat History

 #    Bot                            You        
────────────────────────────────────────────────
 1    action_listen                             
────────────────────────────────────────────────
 2                                        Hello 
                             intent: greet 0.96 
────────────────────────────────────────────────
 3    utter_greet                               
      Hey! How are you?                         
------
? The bot wants to run 'action_listen', correct?  Yes
127.0.0.1 - - [2018-10-28 10:03:28] "POST /conversations/default/execute HTTP/1.1" 200 1540 0.001742
127.0.0.1 - - [2018-10-28 10:03:28] "GET /conversations/default/tracker?include_events=APPLIED HTTP/1.1" 200 1514 0.001130
? Next user input:  I am looking for eat chinese today
127.0.0.1 - - [2018-10-28 10:03:42] "POST /conversations/default/messages HTTP/1.1" 200 2041 0.003747
127.0.0.1 - - [2018-10-28 10:03:42] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 2041 0.001982
**? Is the NLU classification for 'I am looking for eat chinese today' with intent 'mood_great' correct?  No
? What intent is it?       <other>
? Please type the intent name  food
? Please mark the entities using [value](type) notation  I am looking for eat [chinese](cuisine) today**
127.0.0.1 - - [2018-10-28 10:04:18] "PUT /conversations/default/tracker/events HTTP/1.1" 200 1514 0.003241
127.0.0.1 - - [2018-10-28 10:04:18] "POST /conversations/default/messages HTTP/1.1" 200 1505 0.001866
2018-10-28 10:04:18 ERROR    rasa_core.server  - Caught an exception during prediction.
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/server.py", line 340, in predict
    responses = agent.predict_next(sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 317, in predict_next
    return processor.predict_next(sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 102, in predict_next
    self._get_next_action_probabilities(tracker)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 457, in _get_next_action_probabilities
    tracker, self.domain)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 216, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/policies/fallback.py", line 101, in predict_action_probabilities
    nlu_confidence = nlu_data["intent"].get("confidence", 1.0)
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 963, in handle_one_response
    self.run_application()
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 911, in run_application
    self.process_result()
  File "/anaconda3/lib/python3.6/site-packages/gevent/pywsgi.py", line 895, in process_result
    for data in self.result:
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/anaconda3/lib/python3.6/site-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
TypeError: 'Response' object is not iterable
2018-10-28T17:04:18Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '51985', 'HTTP_HOST': 'localhost:5005', (hidden keys: 23)} failed with TypeError

127.0.0.1 - - [2018-10-28 10:04:18] "POST /conversations/default/predict HTTP/1.1" 500 161 0.008780
2018-10-28 10:04:18 ERROR    rasa_core.training.online  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 860, in record_messages
    finetune=finetune)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 589, in _predict_till_next_listen
    response = request_prediction(endpoint, sender_id)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 98, in request_prediction
    return _response_as_json(r)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/online.py", line 62, in _response_as_json
    response.raise_for_status()
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5005/conversations/default/predict

You can see in bold in the above example what I trying to do. Is that supposed to work? I am trying to add a "food" intent to the NLU model along with the corresponding entity, but I always encounter the error.  I have also tried correcting the existing intents and retraining the NLU model, I don't see any update in NLU file. 

I just want to clarify if these functionalities exist and whether I am following the right steps to achieve what I am trying to do!

@tmbo  @akelad

**Comment by thiagodiogo** [comment]
I am having almost the same issue here with Interactive Learning, however the error is a bit different when updating the `nlu_data.md` after the manual trainning:

```
Traceback (most recent call last):
  File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1213, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1063, in _enter_user_message
    lambda a: not a)
  File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 315, in _ask_or_abort
    should_retry = _ask_if_quit(sender_id, endpoint)
  File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 580, in _ask_if_quit
    _write_domain_to_file(domain_path, evts, endpoint)
  File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 793, in _write_domain_to_file
    new_domain = Domain.from_dict(domain_dict)
  File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/domain.py", line 98, in from_dict
    utter_templates = cls.collect_templates(data.get("templates", {}))
  File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/domain.py", line 211, in collect_templates
    for template_key, template_variations in yml_templates.items():
    AttributeError: 'list' object has no attribute 'items'
```
Env:
```
Markdown==3.0.1
rasa-core==0.13.0a5
rasa-core-sdk==0.12.1
rasa-nlu==0.13.8
```
Any idea?  Thank you so much

**Comment by thiagodiogo** [comment]
> I am having almost the same issue here with Interactive Learning, however the error is a bit different when updating the `nlu_data.md` after the manual trainning:
> 
> ```
> Traceback (most recent call last):
>   File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1213, in record_messages
>     _enter_user_message(sender_id, endpoint)
>   File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1063, in _enter_user_message
>     lambda a: not a)
>   File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 315, in _ask_or_abort
>     should_retry = _ask_if_quit(sender_id, endpoint)
>   File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 580, in _ask_if_quit
>     _write_domain_to_file(domain_path, evts, endpoint)
>   File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 793, in _write_domain_to_file
>     new_domain = Domain.from_dict(domain_dict)
>   File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/domain.py", line 98, in from_dict
>     utter_templates = cls.collect_templates(data.get("templates", {}))
>   File "/home/user/anaconda/envs/my_env/lib/python3.6/site-packages/rasa_core/domain.py", line 211, in collect_templates
>     for template_key, template_variations in yml_templates.items():
>     AttributeError: 'list' object has no attribute 'items'
> ```
> Env:
> 
> ```
> Markdown==3.0.1
> rasa-core==0.13.0a5
> rasa-core-sdk==0.12.1
> rasa-nlu==0.13.8
> ```
> Any idea? Thank you so much

**UPDATE:**
Going into the code, just confirmed this problem is only in version `0.13.0a5`. This works fine on `0.12.3` (just tested now)

**Comment by tmbo** [comment]
Mhm how does the template section of your domain yaml look like? This sounds like it is wrongly formatted (should be caught by the yaml validation, but maybe there is something that slipped through) - sounds like the items you put into `"templates"` are a list instead of a dictionary.

**Comment by thiagodiogo** [comment]
@tmbo I think my domain is correct because it's working on `0.12.3` version.

More details here:

Here the interactive train mode works as expected but the SocketIO channel doesn't work:
```
rasa-core==0.12.3
rasa-core-sdk==0.12.1
rasa-nlu==0.13.8
```

Here the SocketIO channel works properly but the interactive train mode doesn't work:
```
rasa-core==0.13.0a5
rasa-core-sdk==0.12.1
rasa-nlu==0.13.8
```

I am using 2 conda envs to use both (rsrsrsrsr) - _have no time to troubleshoot it now_

**Comment by tapos12** [comment]
I also have the same issue as @thiagodiogo had. and I am on rasa-core 0.13.0a4 version

**Comment by tmbo** [comment]
@thiagodiogo @tapos12 I've found the issue you were experiencing, it is fixed in #1634

**Comment by thiagodiogo** [comment]
That's awesome, thanks @tmbo! I will update and test it

**Comment by lo50g3usuresh** [comment]
Awesome! Thanks @tmbo . Just verified and working fine.
